require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GoatsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Goat. As you add validations to Goat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:goat)
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all goats as @goats" do
      goat = Goat.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:goats)).to eq([goat])
    end
  end

  describe "GET #show" do
    it "assigns the requested goat as @goat" do
      goat = Goat.create! valid_attributes
      get :show, {:id => goat.to_param}, valid_session
      expect(assigns(:goat)).to eq(goat)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Goat" do
        expect {
          post :create, {:goat => valid_attributes}, valid_session
        }.to change(Goat, :count).by(1)
      end

      it "assigns a newly created goat as @goat" do
        post :create, {:goat => valid_attributes}, valid_session
        expect(assigns(:goat)).to be_a(Goat)
        expect(assigns(:goat)).to be_persisted
      end

      it "returns 201 Created" do
        post :create, {:goat => valid_attributes}, valid_session
        expect(response.status).to be(201)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved goat as @goat" do
        post :create, {:goat => invalid_attributes}, valid_session
        expect(assigns(:goat)).to be_a_new(Goat)
      end

      it "re-renders the 'new' template" do
        post :create, {:goat => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested goat" do
        goat = Goat.create! valid_attributes
        put :update, {:id => goat.to_param, :goat => new_attributes}, valid_session
        goat.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested goat as @goat" do
        goat = Goat.create! valid_attributes
        put :update, {:id => goat.to_param, :goat => valid_attributes}, valid_session
        expect(assigns(:goat)).to eq(goat)
      end

      it "returns a 200 OK" do
        goat = Goat.create! valid_attributes
        put :update, {:id => goat.to_param, :goat => valid_attributes}, valid_session
        expect(response.status).to be(200)
      end
    end

    context "with invalid params" do
      it "assigns the goat as @goat" do
        goat = Goat.create! valid_attributes
        put :update, {:id => goat.to_param, :goat => invalid_attributes}, valid_session
        expect(assigns(:goat)).to eq(goat)
      end

      it "re-renders the 'edit' template" do
        goat = Goat.create! valid_attributes
        put :update, {:id => goat.to_param, :goat => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested goat" do
      goat = Goat.create! valid_attributes
      expect {
        delete :destroy, {:id => goat.to_param}, valid_session
      }.to change(Goat, :count).by(-1)
    end

    it "sends 204 No content" do
      goat = Goat.create! valid_attributes
      delete :destroy, {:id => goat.to_param}, valid_session
      expect(response.status).to be 204
    end
  end

  describe "POST #reset" do
    it "resets the goats in the db" do
      FactoryGirl.create(:goat)
      expect { post :reset, valid_session }.to change{Goat.count}.from(1).to(4)
    end
  end

end
